### PR TITLE
Replace Travis with Github Actions

### PR DESCRIPTION
**Pull request by alexander-schranz**
| Q                  | A
| ------------------ | ---
| Bug fix?           | no
| New feature?       | no
| BC breaks?         | no
| Deprecations?      | no
| Fixed tickets      | fixes #issuenum
| Related issues/PRs | closes #834
| License            | MIT

#### What's in this PR?

Add Github actions

#### Why?

Replace travis.

#### Example Usage

See https://github.com/alexander-schranz/PHP-FFMpeg/pull/1/checks for the Test Matrix

Github actions will only run when merged in master before they will only run on the fork.

### CODE REVIEW

**Comment by alexander-schranz** [comment]
@Romain This will fix the PHP 5.3 compatibility and move the Tests to Github Action so we have a working CI again.

**Review by jens1o — APPROVED** [review]
lgtm :)

**Comment by jens1o** [comment]
Do you know why GitHub still waits for travis-ci even though the `.travis.yml` was deleted?

**Comment by alexander-schranz** [comment]
@jens1o this is configured in github settings still as "required". Not sure but think its under settings/branches/master. There you can define which CI jobs are required for the project.

**Comment by jens1o** [comment]
@alexander-schranz Unfortunately, I'm not a `Administrator` and cannot change this. Maybe @romainneutron can fix this for us?

**Comment by alexander-schranz** [comment]
Or @Romain maybe who did merge the last things.

**Comment by alexander-schranz** [comment]
Thx then this one can be merged. The CI will only run here after the merge for future pull requests.

**Comment by jens1o** [comment]
Great, thank you for your ongoing efforts regarding this project @alexander-schranz :)

**Comment by alexander-schranz** [comment]
Happy to give something back as a user of the library :)

**Pull request merged**
