### PR TITLE
Update AspectRatio.php

### PR DESCRIPTION
**Pull request by CDNRocket**
Adds more standard aspect ratio

### CODE REVIEW

**Comment by patkar** [comment]
Looks good to me :+1: 

Might have a refactoring on this ^^

**Comment by Romain** [comment]
It looks good to me too.
@hanserdev Could you update your branch with the latest master?
@romainneutron I think this is mergeable, don't you think?

**Comment by jens1o** [comment]
@Romain Why you don't update it with latest master?

**Comment by Romain** [comment]
@jens1o, I cannot do it.
I need @hanserdev to update his branch with master first.

capture d ecran 2017-04-25 a 10 46 42

**Comment by jens1o** [comment]
Ah, in most cases the owner is able to update the branch with just a click...

**Comment by Romain** [comment]
Yep...

**Comment by CDNRocket** [comment]
Oh my god, sorry 👍

**Comment by jens1o** [comment]
Thanks!

**Pull request merged**
