### PR TITLE
Added a getAsBase64() method to Frame object

### PR DESCRIPTION
**Pull request by GuillaumeVerdon**
| Q                  | A
| ------------------ | ---
| Bug fix?           | no
| New feature?       | yes
| BC breaks?         | no
| Deprecations?      | no
| Fixed tickets      | 
| Related issues/PRs | 
| License            | MIT

#### What's in this PR?

For now, when we are generating thumbnails, we are forced to save the thumbnail on the disk. This can be very time consuming in some cases.

My method allow us to retrieve directly base 64 encoded image as a string, so you can embed it into an html  tag or whatever

#### Why?

I had the issue, I am generating a thumbnail to display on a page and I didn't want to save it in a temporary file that would be deleted each time user navigate on a new video

#### Example Usage

```
echo "<img src='data:images/png;base64," . getThumbnail("/home/guillaume/Vidéos/Seigneur des anneaux/01_La Communauté De L'anneau Partie 1.avi") . "' />";

function getThumbnail($videoPath) {
	setlocale(LC_CTYPE, "en_US.UTF-8"); # Else, the process will strip non ascii chars (like é, è, à, etc...)
	$ffmpeg = FFMpeg\FFMpeg::create();
	$movie = $ffmpeg->open($videoPath);

	$frame = $movie->frame(FFMpeg\Coordinate\TimeCode::fromSeconds(60))->getAsBase64();

	return $frame;
}
```

#### Note

- Currently, there is just one test case and it doesn't test a real case with a real frame but it test that the driver send the correct commands to ffmpeg

### CODE REVIEW

**Comment by Romain** [comment]
Hi @GuillaumeVerdon,

The idea is interesting and the implementation seems clean.

I'm just questioning myself if this is worth creating a new function for this, because the code only varies in the last parameters of the FFMPEG request, or if we should modify the save function to add a parameter to define if we generate a new file or get the result as base64. This parameter would be set to generate a new file by default.
This would avoid duplicating the code...

What's your point of view on this?

**Comment by GuillaumeVerdon** [comment]
Yep you're right, creating a new method add a lot of code redundancy

I merged the two logics and the tests, it should be better now.

**Comment by GuillaumeVerdon** [comment]
Is everything ok from your side to release now ?

**Comment by Romain** [comment]
Looks good to me.
I'm waiting for reviews on another PR to merge both at the same time.

**Comment by GuillaumeVerdon** [comment]
Hi @Romain !
Could you let me know when you think it will be merged ?
I need this feature in a personal project :+1:

**Comment by Romain** [comment]
Hi @GuillaumeVerdon, it's likely it will be merged at the beginning of next week.

**Pull request merged**
