### PR TITLE
Add audio metadata filter

### LINKED ISSUE #175: Save metadata changes
Hi, im new here, its posible update the metadata of an audio file, something like

``` php
    $ffmpeg = FFMpeg::create();
    $audio = $ffmpeg->open($file);
    $audio->getFormat()->set('title','my new title');
    $audio->save();

```

### PR DESCRIPTION
**Pull request by shadrech**
| Q                  | A
| ------------------ | ---
| Bug fix?           | no
| New feature?       | yes
| BC breaks?         | no
| Deprecations?      | no
| Fixed tickets      | fixes #175 #120 
| Related issues/PRs | #issuenum
| License            | MIT

#### What's in this PR?

Adds a new Audio Filter. Using ffmpeg -metadata utility we can set metadata values such as title, artist, album etc...
Filter also can add image files to audio files (album artwork)
By not supplying an argument to the filter, it will remove all metadata, including previously set artworks

#### Why?

A simple way to add metadata or album artwork to audio files

#### Example Usage

```php
$ffmpeg = new FFMpeg\FFMpeg::create();
$audio = $ffmpeg->open($file_path);
$audio->addMetadata([
    "title" => "Some Title",
    "album" => "Some Album",
    "artwork" => "/path/to/some/file.jpg"
]);

### CODE REVIEW

**Comment by Romain** [comment]
Hi @shadrech,
Thanks for this PR!

Here are my comments:
- I think we should make priority a parameter of your class, to be able to set it. This what is done with all the other filters. This would allow us to be consistent all over our filters

Otherwise, it looks good to me. Nice job.

**Comment by shadrech** [comment]
Done. Let me know if that will do

**Comment by Romain** [comment]
@shadrech Looks good to me! Thanks

**Comment by shadrech** [comment]
@Romain Let me know (I'm kinda new to open source contribution). What happens now? Do I have to pull in the branch I've made manually to access the new filter or will it be merged to the master branch? Thanks

**Comment by Romain** [comment]
Now someone needs to merge your branch. I've asked @romainneutron if he's ok with your contribution. I can do it, but since I'm new to administrating this bundle, I prefer to refer to him for now.

Then, once it's merged, you can delete your branch, but github will invite you to do so.

Then, I think than Romain needs to prepare a new version with the feature, for it to be available on Packagist.

**Pull request merged**
