### PR TITLE
Added documentation for the watermark filter

### LINKED ISSUE #216: Watermark filter documentation
| Q              | A
| -------------- | ---
| Bug?           | no
| New Feature?   | no
| Version Used   | 0.6.1
| FFmpeg Version | FFmpeg
| OS             | OS X 10.11.4

I just had a hard time getting to understand how the watermark filter worked. I did get it to work, but was wondering if there was a reason it wasn't in the documentation. I think it would make sense in the [filter section](https://github.com/PHP-FFMpeg/PHP-FFMpeg#filters) of the readme. I could throw in the PR if you want. What do you think?

### PR DESCRIPTION
**Pull request by seblavoie**
| Q                  | A
| ------------------ | ---
| Bug fix?           | no
| New feature?       | no
| BC breaks?         | no
| Deprecations?      | no
| Fixed tickets      | fixes #216
| Related issues/PRs | -
| License            | **MIT**

#### What's in this PR?

Added documentation for the watermark filter.

### CODE REVIEW

**Comment by patkar** [comment]
Thank you for the PR. Some open points:

* Please use the provided PR template by GitHub in the future, even for docs.
* Please format the code examples with correct code style (PSR-2) ;)
* Please use backticks for inline formatting of the variable names, e.g. `$watermarkPath`

**Comment by patkar** [comment]
@seblavoie I've edited your PR with the template, please fill in the license (only MIT is accepted) :smile:

**Comment by seblavoie** [comment]
Sure! I think this should be all good now 👍

**Comment by patkar** [comment]
Thanks :+1:

**Pull request merged**
