### PR TITLE
Correct $gop type in VideoFilters->framerate

### PR DESCRIPTION
**Pull request by cuong-tran**
| Q                  | A
| ------------------ | ---
| Bug fix?           | yes
| New feature?       | no
| BC breaks?         | no
| Deprecations?      | no
| Fixed tickets      | fixes #issuenum
| Related issues/PRs | #issuenum
| License            | MIT

#### Why?

Fix type declaration in comment block which would cause some IDE (e.g. PhpStorm) complains warning.

### CODE REVIEW

**Comment by jens1o** [comment]
Nice pr, and looks good to me, but the maintainer is currently inactive... :/

**Comment by Romain** [comment]
@jens1o I have been pretty busy lately.
You've been very active here these last few months. You should ask @romainneutron to add you to the mergers so you can merge PRs. He is the creator and manager of this bundle, though he is inactive today.
If you want, we can handle the PRs together, talking about it. If you have merging access, I'll give you my email address so we could discuss specific issue by email, I'll be more reactive (if you don't flood me with emails... ;)).

**Comment by jens1o** [comment]
I'm in! @Romain Would love to do that. I think that would also be good for this library. I'll write him a email.

**Comment by Romain** [comment]
We need to be very careful on what we merge though...
The last PR you wrote that I merged introduced a bug that the tests should have detected, but haven't. I think, the key challenge is not to merge all the PRs or publish a release every but much more to maintain the stability of the bundle.
When we push a PR or merge one, we need to also do manual tests of video conversion to make sure that no error has been introduced.

**Comment by jens1o** [comment]
Yeah, good suggestion.

**Comment by romainneutron** [comment]
Hello @Romain and @jens1o 

I just granted @jens1o merge access to these repos.
Please be sure to merge code when tests are green, never push force to master, and wait for reviews whenever it's possible.

I trust both of you on loving this code.

**Comment by jens1o** [comment]
Thank you :)
I'll obey to your rules :)

**Pull request merged**
