### PR TITLE
Creation of a setPasses method for the X264 format.

### PR DESCRIPTION
**Pull request by Romain**
| Q                  | A
| ------------------ | ---
| Bug fix?           | no
| New feature?       | yes
| BC breaks?         | no
| Deprecations?      | no
| Fixed tickets      | -
| Related issues/PRs | #250 
| License            | MIT

#### What's in this PR?

This PR adds a method to the Format/Video/X264 class to be able to set the number of passes for this format.

#### Why?

The number of passes may be a potential source of trouble for large files.

### CODE REVIEW

**Comment by Romain** [comment]
@matrunchyk Thanks for approving the changes.
Do you have the ability to merge this request?

**Comment by matrunchyk** [comment]
@Romain Unfortunately I don't. @patkar Please take a look

**Comment by Romain** [comment]
Thanks for your reply.
I have also posted another pull request which implements the waveform feature. Feel free to let me know what you think about it.

**Comment by Romain** [comment]
@patkar, any comment regarding this PR?

**Pull request merged**
