### PR TITLE
Added possibility to extract images without encoding the video.

### LINKED ISSUE #514: how to extract frames without save a video?
the document for extractMultipleFrames is not clear, since we add the folder  to method `extractMultipleFrames`, why we need to add another path to save method?  the folder is the place to save all frames, but specify it there doesn't  work as  expect, we have to extract frames when transcode a video into another format, this is not what we need.
```
$video
    ->filters()
    ->extractMultipleFrames(FFMpeg\Filters\Video\ExtractMultipleFramesFilter::FRAMERATE_EVERY_10SEC, '/path/to/destination/folder/')
    ->synchronize();

$video
    ->save(new FFMpeg\Format\Video\X264(), '/path/to/new/file');
```

### PR DESCRIPTION
**Pull request by biozshock**
Fixes #514 and #494

| Q                  | A
| ------------------ | ---
| Bug fix?           | yes
| New feature?       | yes
| BC breaks?         | no
| Deprecations?      | no
| Fixed tickets      | fixes #514 #494
| Related issues/PRs | #514 #494
| License            | MIT

#### What's in this PR?

PR allows to avoid encoding of the video if you only need to save frame images.

#### Why?

Reduce load on encoding machines.

#### Example Usage

```php
$video->filters()
    ->extractMultipleFrames(ExtractMultipleFramesFilter::FRAMERATE_EVERY_10SEC);

$video->save(new NullFormat(), '/tmp/image%03d.jpg');
```

### CODE REVIEW

**Comment by jens1o** [comment]
Could you please file this against the `v1.x` branch?

**Comment by biozshock** [comment]
@jens1o one that uses a minimum php 7.1? I'd rather merged this into branch that supports 5.6

**Comment by jens1o** [comment]
> one that uses a minimum php 7.1? I'd rather merge this into branch that supports 5.6

Yeah, please, because you are doing multiple bc breaks, and I won't push this into the v0.x branch.

**Comment by jens1o** [comment]
I'll look into this at the weekend, please ping me if I couldn't catch up with it :)

**Comment by EliasDeVos** [comment]
Hi, @jens1o what's the status of this pr ? i also need this and can help if needed

**Comment by jens1o** [comment]
@EliasDeVos Thanks for the ping. :) It would be helpful if you could just push this to master after a rebase. :)

**Comment by biozshock** [comment]
@jens1o @EliasDeVos hello guys. I just noticed this functionality is not yet in the library. Anything i need to do in order to close this properly?

**Pull request closed without merging**
