### PR TITLE
Remove silex support

### PR DESCRIPTION
**Pull request by franmomu**
| Q                  | A
| ------------------ | ---
| Bug fix?           | no
| New feature?       | no
| BC breaks?         | no
| Deprecations?      | yes
| Fixed tickets      | -
| Related issues/PRs | -
| License            | MIT

#### What's in this PR?

Remove Silex support.

#### Why?

Silex was abandoned 3 years ago, removing its support will allow to bump some dependencies.

#### BC Breaks/Deprecations

- `FFMpeg\FFMpegServiceProvider` was deprecated, the user must implement the provider by itself.

### CODE REVIEW

**Comment by franmomu** [comment]
Fridnly ping @Romain, any chance this can be reviewed? 

I wanted to add support for `doctrine/cache` 2 and add `symfony/cache`, but there are conflicts with `silex/silex` 1. It could be upgraded to `silex/silex` 2, but since it was abandoned long time ago I don't think it's worth it.

Travis fail look unrelated, I created https://github.com/PHP-FFMpeg/PHP-FFMpeg/pull/816

**Comment by Romain** [comment]
Sorry I missed this PR @franmomu .
It looks good to me.
Travis failure seems unrelated indeed.

**Comment by Romain** [comment]
So far I can't merge this PR since tests fail. I'm waiting for your PR #816 to pass to merge it and then update this one.

**Comment by franmomu** [comment]
thank you @Romain!

Is it ok to remove support of php < 7.1? I was trying to fix travis and using `bionic` would work but only for php > 7.0: https://github.com/franmomu/PHP-FFMpeg/pull/3/checks?check_run_id=2892240575

**Comment by Romain** [comment]
Hmmm... That's a tough question.
I'd rather keep compability with as much versions as we can. This would be a BC break a we would need to create a new major version.

**Comment by Romain** [comment]
I just realized that there's a `v1.x` branch that has been created by @jens1o but not updated since 2018.
A lot of things have been committed into it, but since it has not been updated for quite some time, I don't think that it's worth taking the risk to use it.

@jens1o what was the point of this branch? What were the breaking changes that you wanted to introduce?

**Comment by franmomu** [comment]
oh, there is a lot of work in those branches. Apparently there are some new interfaces, cleanups, type declarations, coding style, etc.

If a major version is going to be released, I agree about removing support for unsupported php versions, it also would be nice to add coding standards, type declarations (BC break) and maybe some static analysis.

**Comment by franmomu** [comment]
In the meantime, I think travis could work with the last commit, at least it worked in https://github.com/franmomu/PHP-FFMpeg/pull/4

**Comment by franmomu** [comment]
sorry to bother again @Romain, but I think with the last commit travis could work, can you please approve the workflow to see  if it works? thanks!

**Comment by franmomu** [comment]
friendly ping @Romain or @jens1o if you could approve the workflow

**Comment by jens1o** [comment]
It looks like I lack permission to approve Travis CI builds. :(

**Comment by jens1o** [comment]
It might be an idea that the community that is using this project comes up with a fork, as this project seems dead without any maintainer...

**Comment by franmomu** [comment]
No worries, I thought the workflow must be approved before, looks strange.

**Review by thomaspicquet — APPROVED** [review]

**Comment by pascalbaljet** [comment]
Thanks @franmomu!

**Pull request merged**
