### PR TITLE
Add new filter implementing the -an ffmpeg functionality that strips …

### PR DESCRIPTION
**Pull request by alexwybraniec**
| Q | A |
| --- | --- |
| Bug fix? | no |
| New feature? | Yes |
| BC breaks? | no |
| Deprecations? | no |
| Fixed tickets | fixes #issuenum |
| Related issues/PRs | #issuenum |
| License | MIT |
#### What's in this PR?

Add a new video filter, utilising the -an ffmpeg flag to strip audio from a video file.
#### Why?

Needed to be able to remove audio track from video file, couldn't a standard way find way of doing this in the current implementation.
#### Example Usage

``` php
$ffmpeg = FFMpeg\FFMpeg::create();
$video = $ffmpeg->open($input_filename);
$video->filters()->removeAudio();

//Save the file with format

```
#### To Do
- [ ] Create tests

…remove the audio from a video file

### CODE REVIEW

**Comment by Romain** [comment]
The code looks good to me.
Shouldn't we write any tests though?

**Comment by Romain** [comment]
@alexwybraniec In order to validate this PR, could you write the tests that correspond to this feature?
Thanks
Romain

**Comment by alexwybraniec** [comment]
@Romain Happy to write tests, but can you point me in the direction of some project specific documentation about doing so?

**Comment by Romain** [comment]
Hi @alexwybraniec,
You could take in exemple what has been done for other filters, like the SynchronizeFilter.
Look at the tests/Unit/Filters/Video/SynchronizeFilterTest.php file for instance, and create a new one on the same model.
Let me know if you struggle.
R

**Comment by jens1o** [comment]
Any news on this? Otherwise I could write the tests and making a new pr.

**Comment by Romain** [comment]
@jens1o, if you have time to write the tests, yes, please.
I'll try to have a look at your other PRs.

**Comment by jens1o** [comment]
Okay. I expect it to be done tomorrow.

**Comment by travoliti** [comment]
Any updates on this?

**Comment by jens1o** [comment]
Forgot to push it. It is done since the same day I said it... I'll push it in the evening.

**Comment by Romain** [comment]
I created a PR on @alexwybraniec repo with a fix to the conflict.
Could you update your PR please, so I could squash and merge this one?
Thanks
Romain

**Comment by Romain** [comment]
PR #366 fixes this in a nice and simple way.

**Pull request closed without merging**
