### PR TITLE
Fix more tests in PHPUnit 6

### PR DESCRIPTION
**Pull request by carusogabriel**
| Q                  | A
| ------------------ | ---
| Bug fix?           | Yes
| New feature?       | no
| BC breaks?         | Yes
| Deprecations?      | Yes
| Fixed tickets      |  #412 
| Related issues/PRs | #412 
| License            | MIT

Fixed more tests in `PHPUnit 6`, not all.

### CODE REVIEW

**Comment by jens1o** [comment]
Could you work on the tests please?

**Comment by carusogabriel** [comment]
Fixed all of them now :tada:

**Comment by jens1o** [comment]
Oh, that's strange. Tests that are supposed to work are failing. Actually, invalid Framerates should be thrown too... I simplified it too much. :/

**Comment by jens1o** [comment]
Could you file it again please(without that framerate test)? actually, I wanted to pull from the latest commit, but instead, I merged. :/

**Comment by carusogabriel** [comment]
Let's do it in parts? Let's submit:
- Fluent mock definition to avoid `getMock` deprecated alerts;
- `@expectedException` anottations;
- Fix real tests failing;

**Comment by jens1o** [comment]
Good idea. I'm glad you're here to contribute. :)

Let me know if you need some help. :)

**Pull request merged**
