### PR TITLE
Codec Testing [need help with tests]

### LINKED ISSUE #322: Replace libfaac by libmp3lame as the default codec
| Q              | A
| -------------- | ---
| Bug?           | no
| New Feature?   | no
| Version Used   | 0.9.2

#### Actual Behavior

The default codec for the audio is libfaac which is source of errors for a lot of people who don't have this codec installed by default and don't think to set up the codec they want to use in their code.

#### Expected Behavior

We should change this and make libmp3lame the default codec, and also check if the codec is available before setting it.

### PR DESCRIPTION
**Pull request by jens1o**
| Q                  | A
| ------------------ | ---
| Bug fix?           | yes
| New feature?       | yes/no
| BC breaks?         | maybe, libfaac won't be used internally, but it's known for problems
| Deprecations?      | no
| Fixed tickets      | fixes #322 
| Related issues/PRs | #322 , #310 
| License            | MIT

#### What's in this PR?
Basically: Before saving a codec it will be checked wether it is available on the machine. It caches the result of the queries.
The default mp3 codec is now libmp3lame.
I'd modified some tests, so they do not fail on my machine. (Except the one where it is used strictly.)
But I'm still in need of some help, I'm not that experienced in phpunit and the manual wasn't that helpful on this topic. Any point of direction would be cool! 😆 

#### To Do

- [ ] Create tests [help wanted]

### CODE REVIEW

**Comment by jens1o** [comment]
What type of php feature I'd used is new in php 7.x?

**Comment by twoSeats** [comment]
Nobody lending a hand with this huh?

**Comment by jens1o** [comment]
As long as I don't know what new php feature I'd used, I can't bring this to front... 😭

**Comment by Romain** [comment]
The idea is nice.
However, I won't be of much help with the tests, I'm not a phpunit expert either...

**Comment by jens1o** [comment]
Will take another look today

**Pull request closed without merging**
