### PR TITLE
add `libvpx-vp9` to WebM video

### LINKED ISSUE #269: libvpx-vp9 video codec?
| Q              | A
| -------------- | ---
| Version Used   | 0.6.1
| FFmpeg Version | 3.2
| OS             | Ubuntu 14.04

I'm trying to encode my videos to `webm` using the VP9 codec (`libvpx-vp9`):

```
$format = new \FFMpeg\Format\Video\WebM();
$format->setVideoCodec('libvpx-vp9');

$video->save(new \FFMpeg\Format\Video\WebM(), $fileDirectory . '.webm');
```

However, I get the following error when this runs:

> Wrong videocodec value for libvpx-vp9, available formats are libvpx

Am I doing something wrong or does this library doesn't yet support `libvpx-vp9`? It really should.

### PR DESCRIPTION
**Pull request by jens1o**
| Q                  | A
| ------------------ | ---
| Bug fix?           | Yes
| New feature?       | no
| BC breaks?         | no
| Deprecations?      | no
| Fixed tickets      | fixes #269
| Related issues/PRs | #issuenum
| License            | MIT

### CODE REVIEW

**Comment by Romain** [comment]
@jens1o Have tested it with these 2 codecs to make sure that it is properly interpreted?

**Comment by Romain** [comment]
@jens1o, you're missing some tests though. They should be pretty straightforward to add since you just have one option to test.

**Comment by jens1o** [comment]
Yes, I did. FFMpeg looks for each codec and uses the first one it has, that's why it fixes the issue.

**Comment by huglester** [comment]
hello

@jens1o thanks for this. 

with default, `libvpx` - my videos were converted but were 'green'
I have added `libvpx-vp9`
changed the codec to: `new \FFMpeg\Format\Video\WebM('libvorbis', 'libvpx-vp9')`

and it works! thanks. I think this can be safety merged.


this should also fix this issues: https://github.com/PHP-FFMpeg/PHP-FFMpeg/issues/269


thanks

**Comment by jens1o** [comment]
Good ping. I wanted to pull that in. Now let me check whether the tests won't fail again.

**Comment by huglester** [comment]
Hello @jens1o 
just a friendly reminder :)

**Comment by jens1o** [comment]
I know that, but I want to wait for @Romain for at least some time.... Maybe we pull that in in 2-3 days?

**Comment by huglester** [comment]
Sure!:) thanks for sollution btw. Helpec me on mac

**Comment by huglester** [comment]
@jens1o no sign of @Romain  ?:(

**Comment by jens1o** [comment]
Okay, then we might do it now.(when the tests passed)

**Comment by jens1o** [comment]
🎉

**Pull request merged**
