### PR TITLE
Target evenement 3.0 a long side 2.0 and 1.0

### PR DESCRIPTION
**Pull request by WyriHaximus**
| Q                  | A
| ------------------ | ---
| Bug fix?           | no
| New feature?       | no
| BC breaks?         | no
| Deprecations?      | no
| Fixed tickets      | none
| Related issues/PRs | none
| License            | MIT

#### What's in this PR?

Support for evenement 3.0

#### Why?

Evenement 3.0 packs a set of performance improvements for PHP 7 users.

#### BC Breaks/Deprecations

None, although I haven't ran your test suite locally, this is a github.com online edit and PR.

#### To Do

- [X] Create tests (no need for tests)

### CODE REVIEW

**Comment by jens1o** [comment]
First of all, thanks for the pr.
I'll check this out, thanks for the suggestion. :)

**Comment by WyriHaximus** [comment]
No problem at all, took over maintenance of evenement a few weeks ago and now going through the most used packages using to with PR's like these :).

**Comment by loga4** [comment]
can you merge this PR ?

**Comment by jens1o** [comment]
Woah, I'm really bad at resolving to-dos. Sorry.

**Comment by jens1o** [comment]
Thanks again!

**Comment by WyriHaximus** [comment]
@jens1o glad to see this is coming through and you're welcome :+1:

**Pull request merged**
