### PR TITLE
add missing chapter in readme

### PR DESCRIPTION
**Pull request by jens1o**
| Q                  | A
| ------------------ | ---
| Bug fix?           | yes
| New feature?       | no
| BC breaks?         | no
| Deprecations?      | no
| License            | MIT

#### What's in this PR?

adding a chapter and making navigating easier

#### Why?

I'd forgotten to update the readme with my latest (approved) pr, so I'm fixing it now.

### CODE REVIEW

**Comment by jens1o** [comment]
Glad you're back!

**Comment by Romain** [comment]
I'll try to catch up a bit, I've tens of notifications...

**Comment by jens1o** [comment]
I'd supported the users a bit. Is it ok to do so?

**Comment by Romain** [comment]
Sure! Thanks a lot for this!

**Pull request merged**
