### PR TITLE
Add readme notice that there currently is no maintainer for this project

### PR DESCRIPTION
**Pull request by jens1o**

### CODE REVIEW

**Comment by pascalbaljet** [comment]
@jens1o @romainneutron @Romain Let me know if you're looking for a new maintainer for this repo. I'm the creator of the [Laravel FFmpeg package](https://github.com/protonemedia/laravel-ffmpeg), and I'm willing to take over the maintenance of this package to keep it alive 😊

**Comment by Romain** [comment]
Hi @pascalbaljet ,

I'm fine with the idea to have you as a maintainer.
@jens1o ?

**Comment by Romain** [comment]
I checked but I don't think that I have enough rights to add you, @pascalbaljet . Only @romainneutron seems to do.
Romain, can you add Pascal as maintainer?

**Comment by franmomu** [comment]
friendly ping to @romainneutron, it would be nice to move this forward

**Comment by romainneutron** [comment]
Done, @pascalbaljet is now merger

**Pull request closed without merging**
