### PR TITLE
Fixed title

### PR DESCRIPTION
**Pull request by farooghkz**
i simply inserted one space and fixed it's title.

### CODE REVIEW

**Comment by jens1o** [comment]
Hi,

this is also been fixed by #329.

**Comment by farooghkz** [comment]
ok, sorry, i closed this.

**Comment by jens1o** [comment]
nah, don't close it. Maybe something is wrong with my pr, so yours can be merged earlier than mine.

**Comment by farooghkz** [comment]
ok i opened it

**Comment by Romain** [comment]
I think that both PRs will be merged together and the correction will apply anyway.

**Pull request merged**
