### PR TITLE
Creation of a Pad filter which allows the user to resize his video, using black bars

### LINKED ISSUE #227: Pad filter for ffmpeg
| Q | A |
| --- | --- |
| Bug? | no |
| New Feature? | yes |
| Version Used | Specific tag or commit sha |
| FFmpeg Version | FFmpeg or AVConv and version |
| OS | Your OS and version |
#### Actual Behavior

How does PHP-FFMpeg behave at the moment?
#### Expected Behavior

First of all, thanx for this librarie ! Is it possible to implement the padding feature of ffmpeg? So that all the videos can have the same size( height and width) no matter what size they had in the beginning. I know it is possible to do it with ffmpeg but I did not find the feature in this library.

Any one that can help me out? Thanx !

### PR DESCRIPTION
**Pull request by Romain**
| Q                  | A
| ------------------ | ---
| Bug fix?           | no
| New feature?       | yes
| BC breaks?         | no
| Deprecations?      | no
| Fixed tickets      | fixes #227 
| Related issues/PRs | #227 
| License            | MIT

#### What's in this PR?

This PR contains a new filter which allows the user to resize a video with padding.

This is complementary to the resize filter. You don't have to choose a mode of resize, your video will be resized to fit in the new dimensions, and will be wraps into black bars if the ratio of the new video is not the same of the old one.

#### Why?

This is complementary to the resize filter.

I've created a new filter instead of updating the resize one because the FFMPEG command was way too different for this feature.

#### Example Usage

It works in the same way than the resize filter.

```php
$video->filters()->pad($dimension);
```

The pad filter takes one parameter:

- `$dimension`, an instance of `FFMpeg\Coordinate\Dimension`

Don't forget to save it afterwards.

```php
$video->save(new FFMpeg\Format\Video\X264(), $new_file);
```

### CODE REVIEW

**Comment by Romain** [comment]
@romainneutron, @patkar,
Since I wrote this feature, could one of you review it?
Thanks
Romain

**Comment by Romain** [comment]
I've got a question with regards with the test.
When I use locally getMock, I get this warning:

> PHPUnit_Framework_TestCase::getMock() is deprecated, use PHPUnit_Framework_TestCase::createMock() or PHPUnit_Framework_TestCase::getMockBuilder() instead

But then, the tests fail on Travis, which says that createMock doesn't exist.
Do you guys have any idea why we have this inconsistency between local environment and Travis?

**Comment by patkar** [comment]
It's funny that you get a deprecation message, although it doesn't exist. The phpunit version 4.8 is rather old, isn't it?

**Comment by Romain** [comment]
It seems rather old, indeed.
Should we upgrade it?

**Comment by patkar** [comment]
The problem are the PHP versions, since newer phpunit versions dropped support for php < 5.6.

What I always do:

```
        "phpunit/phpunit": "^4.8 ||  ^5.7"
```
so newer php versions use newer phpunit (for performance). Sill you can't use new features from 5.7 because php-ffmpeg still supports the older php versions.

**Comment by Romain** [comment]
Haha, got it.
If we can't switch to newer phpunit features, I'm not sure it's worth upgrading up then.
However, I'm wondering how long we should support PHP5.4 and PHP5.5 since they're quite old too and [no more supported](http://php.net/supported-versions.php)...

On an other topic, what do you think of this PR.
Does it look good to you?

**Comment by Romain** [comment]
I just realize that the CustomFilter allows to do exactly this.
I wonder if we should keep on creating a new filter for this or if we should drop this PR.
Any thought?

**Pull request merged**
