### PR TITLE
Use Doctum instead of Sami

### PR DESCRIPTION
**Pull request by williamdes**
- Fix .gitignore
- Move the process to docs
- Add .gitattributes

| Q                  | A
| ------------------ | ---
| Bug fix?           | no
| New feature?       | no
| BC breaks?         | no
| Deprecations?      | no
| Fixed tickets      | fixes nothing
| Related issues/PRs | nothing
| License            | MIT

#### What's in this PR?

Use [Doctum](https://github.com/code-lts/doctum#readme) instead of Sami

#### Why?

Sami is abandoned, [Doctum](https://github.com/code-lts/doctum#readme) replaces it

#### Example Usage

```bash
./docs/generate-docs.sh
```

#### BC Breaks/Deprecations

n/a

#### To Do

- [ ] Update after merge of review the built output

### CODE REVIEW

**Comment by williamdes** [comment]
Hi @jens1o 
Would you agree to review my work ?

Have a nice day :)

**Comment by williamdes** [comment]
Build is green after 02e0802a6d7a60134d9d5553cb5367d373ca21df :green_circle: 

------

Salut @Romain  
Je t'ai trouvé dans une autre PR ^^
Serait tu intéressé par laisser une review ?

**Comment by Romain** [comment]
Hi @williamdes ,

Thanks for this PR.
I'm not actively maintaining this package anymore. However, I had a look at your PR which seems ok to me from a technical standpoint.
I just have one concern. Doctum 5.1 requires PHP 7.1 to work. This means that `composer.json` would need to be updated accordingly. The thing is, this package works with PHP 5.3.9 and over which covers a large scale of versions of PHP. Deprecating all PHP 5 and PHP 7.0 environments just for Doctum seems like shooting in your own foot for a very small gain to me.

@jens1o What do you think about changing from Sami to Doctum?

**Comment by williamdes** [comment]
> I just have one concern. Doctum 5.1 requires PHP 7.1 to work. This means that composer.json would need to be updated accordingly. The thing is, this package works with PHP 5.3.9 and over which covers a large scale of versions of PHP. Deprecating all PHP 5 and PHP 7.0 environments just for Doctum seems like shooting in your own foot for a very small gain to me.

There is no need for a such change, and this is because Doctum is only a tool used by people or CIs generating the documentation.
So you do not need to care about changing the version restrictions. Only setup a PHP 7 documentation builder and that will be okay :)
This is the reason why I did not add Doctum to the composer json


Thank you for the review :)

**Comment by Romain** [comment]
That sounds good to me then. Since @jens1o is the one really maintaining actively this package, I'd like him to validate this PR before merging it if you don't mind.

**Comment by williamdes** [comment]
> That sounds good to me then. Since @jens1o is the one really maintaining actively this package, I'd like him to validate this PR before merging it if you don't mind.

Sure, let's wait then

**Comment by Romain** [comment]
@williamdes No news from @jens1o, I'll merge your PR.

**Comment by williamdes** [comment]
> @williamdes No news from @jens1o, I'll merge your PR.

Thank you :)

**Pull request merged**
